grant select, insert, update, delete on table public.raiox_intakes to service_role;
grant select, insert, update, delete on table public.vos_cases to service_role;
grant select, insert, update, delete on table public.vos_p8_coverage to service_role;
grant select, insert, update, delete on table public.vos_rx_import_signals to service_role;
grant select, insert, update, delete on table public.vos_evidence to service_role;
grant select, insert, update, delete on table public.vos_ver_entries to service_role;
grant select, insert, update, delete on table public.vos_hypotheses to service_role;
grant select, insert, update, delete on table public.vos_hypothesis_tests to service_role;
grant select, insert, update, delete on table public.vos_conclusions to service_role;
grant select, insert, update, delete on table public.vos_validations to service_role;
grant select, insert, update, delete on table public.vos_gates to service_role;
grant select, insert, update, delete on table public.vos_order_candidates to service_role;
grant select, insert, update, delete on table public.vos_internal_access to service_role;
grant select, insert, update, delete on table public.vos_access_audit to service_role;
grant select, insert, update, delete on table public.crm_contacts to service_role;
grant select, insert, update, delete on table public.crm_opportunities to service_role;
grant select, insert, update, delete on table public.crm_stage_history to service_role;
grant select, insert, update, delete on table public.crm_activities to service_role;

revoke all on table public.raiox_intakes from anon, authenticated;
revoke all on table public.vos_cases from anon, authenticated;
revoke all on table public.vos_p8_coverage from anon, authenticated;
revoke all on table public.vos_rx_import_signals from anon, authenticated;
revoke all on table public.vos_evidence from anon, authenticated;
revoke all on table public.vos_ver_entries from anon, authenticated;
revoke all on table public.vos_hypotheses from anon, authenticated;
revoke all on table public.vos_hypothesis_tests from anon, authenticated;
revoke all on table public.vos_conclusions from anon, authenticated;
revoke all on table public.vos_validations from anon, authenticated;
revoke all on table public.vos_gates from anon, authenticated;
revoke all on table public.vos_order_candidates from anon, authenticated;
revoke all on table public.vos_internal_access from anon, authenticated;
revoke all on table public.vos_access_audit from anon, authenticated;
revoke all on table public.crm_contacts from anon, authenticated;
revoke all on table public.crm_opportunities from anon, authenticated;
revoke all on table public.crm_stage_history from anon, authenticated;
revoke all on table public.crm_activities from anon, authenticated;
