alter table public.client_calendar_events
  add column if not exists status text not null default 'AGENDADO',
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancellation_reason text,
  add column if not exists cancelled_by_email text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'client_calendar_events_status_check'
      and conrelid = 'public.client_calendar_events'::regclass
  ) then
    alter table public.client_calendar_events
      add constraint client_calendar_events_status_check
      check (status in ('AGENDADO', 'CANCELAMENTO_SOLICITADO', 'CANCELADO', 'CONCLUIDO'));
  end if;
end $$;

create table if not exists public.client_email_deliveries (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.crm_clients(id) on delete cascade,
  recipient_email text,
  notification_kind text not null,
  resource_type text not null,
  resource_id uuid not null,
  idempotency_key text not null unique,
  provider text not null default 'RESEND',
  provider_message_id text,
  status text not null default 'PENDING',
  error_code text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sent_at timestamptz,
  constraint client_email_deliveries_status_check
    check (status in ('PENDING', 'SENT', 'SKIPPED', 'FAILED'))
);

create index if not exists client_email_deliveries_client_created_idx
  on public.client_email_deliveries (client_id, created_at desc);

create index if not exists client_email_deliveries_resource_idx
  on public.client_email_deliveries (resource_type, resource_id);

alter table public.client_email_deliveries enable row level security;
revoke all on table public.client_email_deliveries from anon, authenticated;
grant select, insert, update on table public.client_email_deliveries to service_role;
grant usage, select on sequence public.client_email_deliveries_id_seq to service_role;
