import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { sendClientTransactionalEmail } from "../_shared/client-transactional-email.ts";
const PROD='https://ymnegocios.com.br';
const ORIGINS=new Set([PROD,'http://localhost:3000','http://localhost:5173']);
function headers(o:string|null){return {'Access-Control-Allow-Origin':o&&ORIGINS.has(o)?o:PROD,'Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin'};}
function reply(s:number,b:any,o:string|null){return new Response(JSON.stringify(b),{status:s,headers:headers(o)});}
function text(v:any,max=10000){return typeof v==='string'?v.trim().slice(0,max):'';}
function uuid(v:any){return typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
function num(v:any){if(v===null||v===undefined||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null;}
function http(v:string){return /^https?:\/\//i.test(v);}
function validEmail(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);}
function dateOnly(v:any){const s=text(v,20);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null;}
function dateTime(v:any){const s=text(v,60);if(!s)return null;const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString();}
function dateNoon(v:any){const d=dateOnly(v);return d?new Date(d+'T12:00:00-03:00').toISOString():null;}
function slug(v:string){const s=v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,40);return s||'SERVICO';}
function dateEvent(v:any){const d=dateOnly(v);return d?d+'T12:00:00-03:00':null;}

Deno.serve(async(req:Request)=>{
 const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(origin)});if(origin&&!ORIGINS.has(origin))return reply(403,{ok:false,error:'origin_not_allowed'},origin);if(req.method!=='POST')return reply(405,{ok:false,error:'method_not_allowed'},origin);
 const su=Deno.env.get('SUPABASE_URL'),sk=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!su||!sk)return reply(503,{ok:false,error:'storage_not_configured'},origin);const sb=createClient(su,sk,{auth:{persistSession:false,autoRefreshToken:false}});
 const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');const {data:{user},error:ue}=await sb.auth.getUser(token);if(ue||!user?.email)return reply(401,{ok:false,error:'invalid_session'},origin);const email=user.email.toLowerCase();const {data:access,error:ae}=await sb.from('vos_internal_access').select('role,active').eq('email',email).maybeSingle();if(ae||!access?.active)return reply(403,{ok:false,error:'forbidden'},origin);const role=access.role;
 let b:any;try{b=await req.json();}catch{return reply(400,{ok:false,error:'invalid_json'},origin);}const action=text(b.action,80);
 async function audit(event:string,meta:any){await sb.from('vos_access_audit').insert({email,role,event,metadata:meta});}
 async function getClientPortal(clientId:string){
  const [c,s,a,d,ap,ac,n,pref]=await Promise.all([
   sb.from('crm_clients').select('id,status,became_client_at,notes,source_intake_id,source_case_id,source_opportunity_id,contact:crm_contacts(id,name,business_name,email,phone,source,city_state,segment,decision_maker,website_url,linkedin_url,instagram_url,google_url,other_url,notes)').eq('id',clientId).maybeSingle(),
   sb.from('crm_client_services').select('id,service_code,service_name,service_type,status,contracted_value,monthly_value,recurrence_months,start_date,end_date,next_billing_date,notes,project:client_project_meta(*),payments:crm_payments(id,amount,status,payment_date,paid_at,due_date,payment_method,competence_month,notes)').eq('client_id',clientId).order('created_at',{ascending:true}),
   sb.from('client_portal_access').select('id,email,role,active,source,invited_at,onboarding_completed_at,last_login_at').eq('client_id',clientId).order('created_at',{ascending:true}),
   sb.from('client_documents').select('*').eq('client_id',clientId).order('created_at',{ascending:false}),
   sb.from('client_approval_items').select('*,versions:client_approval_versions(*),actions:client_approval_actions(id,version_id,action,comment,actor_type,actor_email,created_at)').eq('client_id',clientId).order('created_at',{ascending:false}),
   sb.from('client_calendar_events').select('*').eq('client_id',clientId).order('starts_at',{ascending:true}),
   sb.from('client_notifications').select('*').eq('client_id',clientId).order('created_at',{ascending:false}).limit(100),
   sb.from('client_communication_preferences').select('*').eq('client_id',clientId).order('created_at',{ascending:true})
  ]);const er=c.error||s.error||a.error||d.error||ap.error||ac.error||n.error||pref.error;if(er)throw er;if(!c.data)throw new Error('client_not_found');return {client:c.data,services:s.data||[],access:a.data||[],documents:d.data||[],approvals:ap.data||[],calendar:ac.data||[],notifications:n.data||[],preferences:pref.data||[]};
 }
 async function listClients(){
  const [cq,aq,pq]=await Promise.all([
   sb.from('crm_clients').select('id,status,became_client_at,notes,created_at,updated_at,source_intake_id,source_case_id,source_opportunity_id,contact:crm_contacts(id,name,business_name,email,phone,source,city_state,segment,decision_maker),services:crm_client_services(id,service_name,service_type,status,contracted_value,monthly_value,start_date,end_date,next_billing_date)').order('became_client_at',{ascending:false}),
   sb.from('client_portal_access').select('id,client_id,email,active,last_login_at,onboarding_completed_at,source').order('created_at',{ascending:true}),
   sb.from('client_approval_items').select('id,client_id,status').in('status',['AGUARDANDO_APROVACAO','AJUSTE_SOLICITADO'])
  ]);const er=cq.error||aq.error||pq.error;if(er)throw er;const acc=new Map<string,any[]>(),pend=new Map<string,number>();for(const a of aq.data||[]){const x=acc.get(a.client_id)||[];x.push(a);acc.set(a.client_id,x)}for(const p of pq.data||[])pend.set(p.client_id,(pend.get(p.client_id)||0)+1);return (cq.data||[]).map((c:any)=>({...c,access:acc.get(c.id)||[],pending_approvals:pend.get(c.id)||0}));
 }
 async function globalCalendar(){
  const [clients,events,approvals,projects,payments,services]=await Promise.all([
   sb.from('crm_clients').select('id,status,contact:crm_contacts(name,business_name,email)').eq('status','ATIVO'),
   sb.from('client_calendar_events').select('id,client_id,client_service_id,title,description,event_type,starts_at,ends_at,all_day,external_url,visible_to_client,status,cancelled_at,cancellation_reason,cancelled_by_email').order('starts_at',{ascending:true}).limit(1000),
   sb.from('client_approval_items').select('id,client_id,title,status,due_at,scheduled_at').neq('status','CANCELADO').limit(1000),
   sb.from('client_project_meta').select('id,client_id,client_service_id,next_step,next_step_due_at,portal_status').not('next_step_due_at','is',null).limit(1000),
   sb.from('crm_payments').select('id,client_service_id,amount,status,due_date').eq('status','PREVISTO').not('due_date','is',null).limit(1000),
   sb.from('crm_client_services').select('id,client_id,service_name,next_billing_date,status').limit(1000)
  ]);const er=clients.error||events.error||approvals.error||projects.error||payments.error||services.error;if(er)throw er;const names=new Map<string,string>();for(const c of clients.data||[]){const ct=(c as any).contact||{};names.set(c.id,ct.business_name||ct.name||'Cliente')}const svc=new Map<string,any>();for(const s of services.data||[])svc.set(s.id,s);const out:any[]=[];
  for(const e of events.data||[])out.push({id:'EV_'+e.id,source:'CALENDARIO',source_id:e.id,client_id:e.client_id,client_name:names.get(e.client_id)||'Cliente',service_id:e.client_service_id,title:e.title,description:e.description,kind:e.event_type,starts_at:e.starts_at,ends_at:e.ends_at,all_day:e.all_day,external_url:e.external_url,visible_to_client:e.visible_to_client,status:e.status,cancelled_at:e.cancelled_at,cancellation_reason:e.cancellation_reason,cancelled_by_email:e.cancelled_by_email});
  for(const a of approvals.data||[]){if(a.due_at)out.push({id:'APD_'+a.id,source:'APROVACAO',source_id:a.id,client_id:a.client_id,client_name:names.get(a.client_id)||'Cliente',title:'Prazo de aprovação · '+a.title,kind:'APROVACAO',starts_at:a.due_at,status:a.status});if(a.scheduled_at)out.push({id:'APS_'+a.id,source:'APROVACAO',source_id:a.id,client_id:a.client_id,client_name:names.get(a.client_id)||'Cliente',title:'Publicação prevista · '+a.title,kind:'PUBLICACAO',starts_at:a.scheduled_at,status:a.status});}
  for(const p of projects.data||[]){if(p.next_step_due_at)out.push({id:'PR_'+p.id,source:'PROJETO',source_id:p.id,client_id:p.client_id,client_name:names.get(p.client_id)||'Cliente',service_id:p.client_service_id,title:p.next_step||'Próximo passo do projeto',kind:'PROXIMO_PASSO',starts_at:p.next_step_due_at,status:p.portal_status});}
  for(const p of payments.data||[]){const s=svc.get(p.client_service_id);if(!s)continue;out.push({id:'PAY_'+p.id,source:'FINANCEIRO',source_id:p.id,client_id:s.client_id,client_name:names.get(s.client_id)||'Cliente',service_id:s.id,title:'Vencimento · '+s.service_name,description:String(p.amount??''),kind:'FINANCEIRO',starts_at:dateEvent(p.due_date),status:p.status,amount:p.amount});}
  out.sort((x,y)=>String(x.starts_at||'').localeCompare(String(y.starts_at||'')));return out;
 }
 try{
  if(action==='ADMIN_OVERVIEW'){const [clients,calendar]=await Promise.all([listClients(),globalCalendar()]);const now=Date.now(),future=calendar.filter((x:any)=>x.status!=='CANCELADO'&&new Date(x.starts_at).getTime()>=now);return reply(200,{ok:true,clients,calendar,kpis:{active_clients:clients.filter((c:any)=>c.status==='ATIVO').length,total_clients:clients.length,portal_enabled:clients.filter((c:any)=>c.access.some((a:any)=>a.active)).length,pending_approvals:clients.reduce((n:number,c:any)=>n+(c.pending_approvals||0),0),upcoming_30d:future.filter((x:any)=>new Date(x.starts_at).getTime()<=now+30*86400000).length}},origin);}
  if(action==='LIST_CLIENTS'){return reply(200,{ok:true,clients:await listClients()},origin);}
  if(action==='LIST_GLOBAL_CALENDAR'){return reply(200,{ok:true,calendar:await globalCalendar()},origin);}
  if(action==='GET_CLIENT_PORTAL'&&uuid(b.client_id)){const data=await getClientPortal(b.client_id);return reply(200,{ok:true,data},origin);}
  if(action==='CREATE_CLIENT'){
   const name=text(b.name,500),business=text(b.business_name,500),e=text(b.email,500).toLowerCase();if(!name&&!business)return reply(400,{ok:false,error:'name_or_business_required'},origin);if(!e||!validEmail(e))return reply(400,{ok:false,error:'valid_email_required',detail:'Informe um e-mail válido para o acesso da Área do Cliente.'},origin);for(const f of ['website_url','linkedin_url','instagram_url','google_url','other_url']){const v=text(b[f],2000);if(v&&!http(v))return reply(400,{ok:false,error:`${f}_must_be_http`},origin);}
   let contact:any=null,createdContact=false;const existing=await sb.from('crm_contacts').select('*').ilike('email',e).limit(1).maybeSingle();if(existing.error)throw existing.error;if(existing.data){const cc=await sb.from('crm_clients').select('id').eq('contact_id',existing.data.id).maybeSingle();if(cc.error)throw cc.error;if(cc.data)return reply(409,{ok:false,error:'client_already_exists',client_id:cc.data.id},origin);const patch:any={name:name||existing.data.name,business_name:business||existing.data.business_name,email:e,phone:text(b.phone,160)||existing.data.phone,source:text(b.source,500)||existing.data.source||'CADASTRO_ADMIN',city_state:text(b.city_state,300)||existing.data.city_state,segment:text(b.segment,800)||existing.data.segment,decision_maker:text(b.decision_maker,500)||name||existing.data.decision_maker,website_url:text(b.website_url,2000)||existing.data.website_url,linkedin_url:text(b.linkedin_url,2000)||existing.data.linkedin_url,instagram_url:text(b.instagram_url,2000)||existing.data.instagram_url,google_url:text(b.google_url,2000)||existing.data.google_url,other_url:text(b.other_url,2000)||existing.data.other_url,notes:text(b.contact_notes,10000)||existing.data.notes,active:true,owner_email:email,updated_at:new Date().toISOString()};const uq=await sb.from('crm_contacts').update(patch).eq('id',existing.data.id).select().single();if(uq.error)throw uq.error;contact=uq.data;}else{const iq=await sb.from('crm_contacts').insert({name:name||null,business_name:business||null,email:e,phone:text(b.phone,160)||null,source:text(b.source,500)||'CADASTRO_ADMIN',owner_email:email,notes:text(b.contact_notes,10000)||null,active:true,city_state:text(b.city_state,300)||null,segment:text(b.segment,800)||null,decision_maker:text(b.decision_maker,500)||name||null,website_url:text(b.website_url,2000)||null,linkedin_url:text(b.linkedin_url,2000)||null,instagram_url:text(b.instagram_url,2000)||null,google_url:text(b.google_url,2000)||null,other_url:text(b.other_url,2000)||null}).select().single();if(iq.error)throw iq.error;contact=iq.data;createdContact=true;}
   const cq=await sb.from('crm_clients').insert({contact_id:contact.id,status:'ATIVO',became_client_at:dateNoon(b.became_client_at)||new Date().toISOString(),notes:text(b.client_notes,10000)||null,updated_by:email}).select().single();if(cq.error){if(createdContact)await sb.from('crm_contacts').delete().eq('id',contact.id);throw cq.error;}const client=cq.data;await sb.from('client_portal_access').upsert({client_id:client.id,email:e,active:true,source:'ADMIN',created_by:email,updated_by:email},{onConflict:'client_id,email'});
   let service:any=null,service_warning:string|null=null;const serviceName=text(b.service_name,500);if(serviceName){const sv={client_id:client.id,service_code:text(b.service_code,120)||slug(serviceName),service_name:serviceName,service_type:['AVULSO','RECORRENTE'].includes(b.service_type)?b.service_type:'AVULSO',status:['CONTRATADO','EM_EXECUCAO','CONCLUIDO','PAUSADO','CANCELADO'].includes(b.service_status)?b.service_status:'CONTRATADO',contracted_value:num(b.contracted_value),monthly_value:num(b.monthly_value),recurrence_months:num(b.recurrence_months),start_date:dateOnly(b.start_date),end_date:dateOnly(b.end_date),next_billing_date:dateOnly(b.next_billing_date),notes:text(b.service_notes,6000)||null,updated_by:email};const sq=await sb.from('crm_client_services').insert(sv).select().single();if(sq.error)service_warning=sq.error.message;else service=sq.data;}
   await audit('CENTRAL_YM_CLIENT_CREATED',{client_id:client.id,contact_id:contact.id,service_id:service?.id||null,email:e});return reply(200,{ok:true,client,contact,service,service_warning},origin);
  }
  if(action==='UPDATE_CLIENT_PROFILE'&&uuid(b.client_id)){
   const cq=await sb.from('crm_clients').select('id,contact_id').eq('id',b.client_id).maybeSingle();if(cq.error)throw cq.error;if(!cq.data)return reply(404,{ok:false,error:'client_not_found'},origin);const e=text(b.email,500).toLowerCase();if(e&&!validEmail(e))return reply(400,{ok:false,error:'invalid_email'},origin);for(const f of ['website_url','linkedin_url','instagram_url','google_url','other_url']){const v=text(b[f],2000);if(v&&!http(v))return reply(400,{ok:false,error:`${f}_must_be_http`},origin);}const patch:any={name:text(b.name,500)||null,business_name:text(b.business_name,500)||null,email:e||null,phone:text(b.phone,160)||null,source:text(b.source,500)||null,city_state:text(b.city_state,300)||null,segment:text(b.segment,800)||null,decision_maker:text(b.decision_maker,500)||null,website_url:text(b.website_url,2000)||null,linkedin_url:text(b.linkedin_url,2000)||null,instagram_url:text(b.instagram_url,2000)||null,google_url:text(b.google_url,2000)||null,other_url:text(b.other_url,2000)||null,notes:text(b.contact_notes,10000)||null,updated_at:new Date().toISOString()};const uq=await sb.from('crm_contacts').update(patch).eq('id',cq.data.contact_id).select().single();if(uq.error)throw uq.error;const cp:any={status:['ATIVO','INATIVO'].includes(b.status)?b.status:'ATIVO',notes:text(b.client_notes,10000)||null,updated_by:email,updated_at:new Date().toISOString()};const became=dateNoon(b.became_client_at);if(became)cp.became_client_at=became;const cl=await sb.from('crm_clients').update(cp).eq('id',b.client_id).select().single();if(cl.error)throw cl.error;if(e)await sb.from('client_portal_access').upsert({client_id:b.client_id,email:e,active:true,source:'ADMIN',created_by:email,updated_by:email},{onConflict:'client_id,email'});await audit('CENTRAL_YM_CLIENT_PROFILE_UPDATED',{client_id:b.client_id});return reply(200,{ok:true,client:cl.data,contact:uq.data},origin);
  }
  if(action==='CREATE_SERVICE'&&uuid(b.client_id)){
   const name=text(b.service_name,500);if(!name)return reply(400,{ok:false,error:'service_name_required'},origin);const chk=await sb.from('crm_clients').select('id').eq('id',b.client_id).maybeSingle();if(chk.error)throw chk.error;if(!chk.data)return reply(404,{ok:false,error:'client_not_found'},origin);const row={client_id:b.client_id,service_code:text(b.service_code,120)||slug(name),service_name:name,service_type:['AVULSO','RECORRENTE'].includes(b.service_type)?b.service_type:'AVULSO',status:['CONTRATADO','EM_EXECUCAO','CONCLUIDO','PAUSADO','CANCELADO'].includes(b.service_status)?b.service_status:'CONTRATADO',contracted_value:num(b.contracted_value),monthly_value:num(b.monthly_value),recurrence_months:num(b.recurrence_months),start_date:dateOnly(b.start_date),end_date:dateOnly(b.end_date),next_billing_date:dateOnly(b.next_billing_date),notes:text(b.service_notes,6000)||null,updated_by:email};const q=await sb.from('crm_client_services').insert(row).select().single();if(q.error)throw q.error;await audit('CENTRAL_YM_SERVICE_CREATED',{client_id:b.client_id,service_id:q.data.id});return reply(200,{ok:true,service:q.data},origin);
  }
  if(action==='ENSURE_ACCESS'&&uuid(b.client_id)){
   const cq=await sb.from('crm_clients').select('id,status,source_intake_id,contact:crm_contacts(email)').eq('id',b.client_id).maybeSingle();if(cq.error)throw cq.error;if(!cq.data)return reply(404,{ok:false,error:'client_not_found'},origin);let e=text(b.email,500).toLowerCase()||text((cq.data as any).contact?.email,500).toLowerCase();if(!e||!validEmail(e))return reply(400,{ok:false,error:'valid_email_required'},origin);const source=(cq.data as any).source_intake_id?'RAIOX':'ADMIN';const q=await sb.from('client_portal_access').upsert({client_id:b.client_id,email:e,active:true,source,updated_by:email,created_by:email},{onConflict:'client_id,email'}).select().single();if(q.error)throw q.error;await audit('CENTRAL_YM_ACCESS_ENABLED',{client_id:b.client_id,access_email:e});return reply(200,{ok:true,access:q.data},origin);
  }
  if(action==='SET_ACCESS_ACTIVE'&&uuid(b.access_id)){const q=await sb.from('client_portal_access').update({active:!!b.active,updated_by:email}).eq('id',b.access_id).select().single();if(q.error)throw q.error;await audit('CENTRAL_YM_ACCESS_STATUS',{access_id:b.access_id,active:!!b.active});return reply(200,{ok:true,access:q.data},origin);}
  if(action==='UPSERT_PROJECT_META'&&uuid(b.client_id)&&uuid(b.client_service_id)){
   const progress=Math.max(0,Math.min(100,Math.round(num(b.progress_pct)??0)));const st=['PLANEJADO','EM_ANDAMENTO','AGUARDANDO_CLIENTE','PAUSADO','CONCLUIDO','CANCELADO'].includes(b.portal_status)?b.portal_status:'PLANEJADO';const row={client_id:b.client_id,client_service_id:b.client_service_id,display_name:text(b.display_name,500)||null,portal_status:st,progress_pct:progress,current_phase:text(b.current_phase,300)||null,summary:text(b.summary,6000)||null,next_step:text(b.next_step,3000)||null,next_step_due_at:dateTime(b.next_step_due_at),visible_to_client:b.visible_to_client!==false,updated_by:email,created_by:email};const q=await sb.from('client_project_meta').upsert(row,{onConflict:'client_service_id'}).select().single();if(q.error)throw q.error;return reply(200,{ok:true,project:q.data},origin);
  }
  if(action==='UPSERT_EVENT'&&uuid(b.client_id)){
   const starts=dateTime(b.starts_at);if(!starts)return reply(400,{ok:false,error:'starts_at_required'},origin);const type=['REUNIAO','ENTREGA','PUBLICACAO','APROVACAO','FINANCEIRO','MARCO','OUTRO'].includes(b.event_type)?b.event_type:'OUTRO';const row:any={client_id:b.client_id,client_service_id:uuid(b.client_service_id)?b.client_service_id:null,title:text(b.title,500),description:text(b.description,6000)||null,event_type:type,starts_at:starts,ends_at:dateTime(b.ends_at),all_day:!!b.all_day,external_url:text(b.external_url,2000)||null,visible_to_client:b.visible_to_client!==false,updated_by:email};if(!row.title)return reply(400,{ok:false,error:'title_required'},origin);if(row.external_url&&!http(row.external_url))return reply(400,{ok:false,error:'url_must_be_http'},origin);let q;if(uuid(b.id))q=await sb.from('client_calendar_events').update(row).eq('id',b.id).eq('client_id',b.client_id).select().single();else q=await sb.from('client_calendar_events').insert({...row,created_by:email}).select().single();if(q.error)throw q.error;
   let emailDelivery:any=null;
   if(row.visible_to_client&&['REUNIAO','ENTREGA','APROVACAO'].includes(type)){
    await sb.from('client_notifications').insert({client_id:b.client_id,notification_type:type,title:type==='REUNIAO'?'Novo compromisso agendado':type==='ENTREGA'?'Nova entrega agendada':'Nova aprovação agendada',message:row.title,target_url:'/areadocliente#calendario',created_by:email});
    emailDelivery=await sendClientTransactionalEmail({sb,clientId:b.client_id,kind:'AGENDA',resourceType:'CALENDAR_EVENT',resourceId:q.data.id,title:row.title,description:row.description,scheduledAt:q.data.starts_at,externalUrl:row.external_url,portalHash:'calendario',allowCancellation:type==='REUNIAO'});
   }
   return reply(200,{ok:true,event:q.data,email_delivery:emailDelivery},origin);
  }
  if(action==='DELETE_EVENT'&&uuid(b.client_id)&&uuid(b.id)){const q=await sb.from('client_calendar_events').delete().eq('id',b.id).eq('client_id',b.client_id);if(q.error)throw q.error;return reply(200,{ok:true},origin);}
  if(action==='UPSERT_DOCUMENT'&&uuid(b.client_id)){
   const url=text(b.drive_url,2000);if(!http(url))return reply(400,{ok:false,error:'drive_url_required'},origin);const cat=['NOTA_FISCAL','CONTRATO','ENTREGAVEL','ESTRATEGIA','CONTEUDO','FINANCEIRO','IDENTIDADE','OUTRO'].includes(b.category)?b.category:'OUTRO';const row:any={client_id:b.client_id,client_service_id:uuid(b.client_service_id)?b.client_service_id:null,title:text(b.title,500),category:cat,drive_url:url,version_label:text(b.version_label,100)||null,competence_month:/^\d{4}-\d{2}$/.test(text(b.competence_month,20))?text(b.competence_month,20)+'-01':null,description:text(b.description,5000)||null,visible_to_client:b.visible_to_client!==false,updated_by:email};if(!row.title)return reply(400,{ok:false,error:'title_required'},origin);let q;if(uuid(b.id))q=await sb.from('client_documents').update(row).eq('id',b.id).eq('client_id',b.client_id).select().single();else q=await sb.from('client_documents').insert({...row,created_by:email}).select().single();if(q.error)throw q.error;
   let emailDelivery:any=null;if(row.visible_to_client){await sb.from('client_notifications').insert({client_id:b.client_id,notification_type:'ARQUIVO',title:'Novo arquivo disponível',message:row.title,target_url:'/areadocliente#documentos',created_by:email});emailDelivery=await sendClientTransactionalEmail({sb,clientId:b.client_id,kind:'ARQUIVO',resourceType:'DOCUMENT',resourceId:q.data.id,title:row.title,description:row.description,externalUrl:url,portalHash:'documentos'});}return reply(200,{ok:true,document:q.data,email_delivery:emailDelivery},origin);
  }
  if(action==='DELETE_DOCUMENT'&&uuid(b.client_id)&&uuid(b.id)){const q=await sb.from('client_documents').delete().eq('id',b.id).eq('client_id',b.client_id);if(q.error)throw q.error;return reply(200,{ok:true},origin);}
  if(action==='CREATE_APPROVAL'&&uuid(b.client_id)){
   const title=text(b.title,500),url=text(b.drive_url,2000);if(!title||!http(url))return reply(400,{ok:false,error:'title_and_drive_url_required'},origin);const iq=await sb.from('client_approval_items').insert({client_id:b.client_id,client_service_id:uuid(b.client_service_id)?b.client_service_id:null,title,content_type:text(b.content_type,200)||null,description:text(b.description,5000)||null,status:'AGUARDANDO_APROVACAO',due_at:dateTime(b.due_at),scheduled_at:dateTime(b.scheduled_at),visible_to_client:true,created_by:email,updated_by:email}).select().single();if(iq.error)throw iq.error;const vq=await sb.from('client_approval_versions').insert({approval_id:iq.data.id,version_number:1,drive_url:url,notes:text(b.version_notes,3000)||null,created_by:email}).select().single();if(vq.error)throw vq.error;await sb.from('client_notifications').insert({client_id:b.client_id,notification_type:'APROVACAO',title:'Novo conteúdo para aprovação',message:title,target_url:'/areadocliente#aprovacoes',created_by:email});const emailDelivery=await sendClientTransactionalEmail({sb,clientId:b.client_id,kind:'APROVACAO',resourceType:'APPROVAL',resourceId:iq.data.id,title,description:iq.data.description,scheduledAt:iq.data.due_at||iq.data.scheduled_at,externalUrl:url,portalHash:'aprovacoes'});return reply(200,{ok:true,approval:iq.data,version:vq.data,email_delivery:emailDelivery},origin);
  }
  if(action==='ADD_APPROVAL_VERSION'&&uuid(b.client_id)&&uuid(b.approval_id)){
   const url=text(b.drive_url,2000);if(!http(url))return reply(400,{ok:false,error:'drive_url_required'},origin);const chk=await sb.from('client_approval_items').select('id,title,description,due_at,scheduled_at').eq('id',b.approval_id).eq('client_id',b.client_id).maybeSingle();if(chk.error)throw chk.error;if(!chk.data)return reply(404,{ok:false,error:'approval_not_found'},origin);const mx=await sb.from('client_approval_versions').select('version_number').eq('approval_id',b.approval_id).order('version_number',{ascending:false}).limit(1).maybeSingle();if(mx.error)throw mx.error;const vn=(mx.data?.version_number||0)+1;const q=await sb.from('client_approval_versions').insert({approval_id:b.approval_id,version_number:vn,drive_url:url,notes:text(b.version_notes,3000)||null,created_by:email}).select().single();if(q.error)throw q.error;await sb.from('client_approval_items').update({status:'AGUARDANDO_APROVACAO',updated_by:email}).eq('id',b.approval_id);await sb.from('client_notifications').insert({client_id:b.client_id,notification_type:'APROVACAO',title:'Nova versão para aprovação',message:(chk.data as any).title,target_url:'/areadocliente#aprovacoes',created_by:email});const emailDelivery=await sendClientTransactionalEmail({sb,clientId:b.client_id,kind:'APROVACAO',resourceType:'APPROVAL_VERSION',resourceId:q.data.id,title:`Nova versão · ${(chk.data as any).title}`,description:(chk.data as any).description,scheduledAt:(chk.data as any).due_at||(chk.data as any).scheduled_at,externalUrl:url,portalHash:'aprovacoes'});return reply(200,{ok:true,version:q.data,email_delivery:emailDelivery},origin);
  }
  if(action==='UPDATE_APPROVAL'&&uuid(b.client_id)&&uuid(b.approval_id)){
   const st=['EM_PRODUCAO','AGUARDANDO_APROVACAO','AJUSTE_SOLICITADO','APROVADO','PUBLICADO','CANCELADO'].includes(b.status)?b.status:null;const patch:any={title:text(b.title,500)||undefined,content_type:text(b.content_type,200)||null,description:text(b.description,5000)||null,due_at:dateTime(b.due_at),scheduled_at:dateTime(b.scheduled_at),updated_by:email};if(st)patch.status=st;Object.keys(patch).forEach(k=>patch[k]===undefined&&delete patch[k]);const q=await sb.from('client_approval_items').update(patch).eq('id',b.approval_id).eq('client_id',b.client_id).select().single();if(q.error)throw q.error;return reply(200,{ok:true,approval:q.data},origin);
  }
  if(action==='CREATE_NOTIFICATION'&&uuid(b.client_id)){const title=text(b.title,500);if(!title)return reply(400,{ok:false,error:'title_required'},origin);const q=await sb.from('client_notifications').insert({client_id:b.client_id,notification_type:text(b.notification_type,120)||'GERAL',title,message:text(b.message,3000)||null,target_url:text(b.target_url,2000)||null,created_by:email}).select().single();if(q.error)throw q.error;return reply(200,{ok:true,notification:q.data},origin);}
  if(action==='LIST_ASSETS'){const q=await sb.from('institutional_assets').select('*').order('status').order('category').order('sort_order').order('title');if(q.error)throw q.error;return reply(200,{ok:true,assets:q.data||[]},origin);}
  if(action==='UPSERT_ASSET'){
   const url=text(b.drive_url,2000),title=text(b.title,500);if(!title||!http(url))return reply(400,{ok:false,error:'title_and_drive_url_required'},origin);const category=['MARCA','INSTITUCIONAL','COMERCIAL','COMUNICACAO','SOCIAL_CONTEUDO','DOCUMENTOS','METODO_VOS','OUTRO'].includes(b.category)?b.category:'OUTRO';const status=['OFICIAL','EM_REVISAO','ARQUIVADO'].includes(b.status)?b.status:'OFICIAL';const row:any={category,title,description:text(b.description,5000)||null,asset_type:text(b.asset_type,200)||null,drive_url:url,version_label:text(b.version_label,100)||null,status,sort_order:Math.round(num(b.sort_order)??100),updated_by:email};let q;if(uuid(b.id))q=await sb.from('institutional_assets').update(row).eq('id',b.id).select().single();else q=await sb.from('institutional_assets').insert({...row,created_by:email}).select().single();if(q.error)throw q.error;await audit('CENTRAL_YM_IDENTITY_ASSET_UPSERT',{asset_id:q.data.id,status,category});return reply(200,{ok:true,asset:q.data},origin);
  }
  if(action==='ARCHIVE_ASSET'&&uuid(b.id)){const q=await sb.from('institutional_assets').update({status:'ARQUIVADO',updated_by:email}).eq('id',b.id).select().single();if(q.error)throw q.error;return reply(200,{ok:true,asset:q.data},origin);}
  return reply(400,{ok:false,error:'unsupported_action'},origin);
 }catch(e:any){console.error('central-ym-admin',action,e?.message||e);return reply(409,{ok:false,error:'operation_failed',detail:String(e?.message||e).slice(0,600)},origin);}
});
